---
title: ""
author: "Shane Kercheval"
output:
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(scales)
library(knitr)

options(scipen=999) # non-scientific notation
options(dplyr.summarise.inform=F)

theme_set(theme_light())

GOLDEN_RATIO <- 1.61803398875
```

```{r data, echo=FALSE}
data(mtcars)
mtcars$car <- rownames(mtcars)
```

```{r snippet_name, echo=FALSE, fig.width=6}
mtcars %>%
    ggplot(aes(x=mpg, y=hp)) +
    geom_point() +
    geom_text(aes(label=car), check_overlap=TRUE, vjust=-0.5) +
    #scale_x_date(labels = rt_pretty_date_label(date_floor, date_break_format), breaks=date_breaks_width, limits=date_limits) +
    scale_y_continuous(breaks=pretty_breaks(10)) +
    expand_limits(y=0) +
    #scale_fill_manual(values=rt_colors()) +
    theme_light(base_size=12) +
    theme(aspect.ratio = 1/1.61803398875,
          legend.position = 'none',
          axis.text.x=element_text(angle=30, hjust=1)) +
    labs(title="MPG vs HP",
         #subtitle="",
         #x="",
         #y="",
         caption="")
```

```{r include=FALSE}
knitr::knit_exit()
```
